version: "3"

services:
    design-django:
        container_name: design-django
        build:
            context: .
            dockerfile: ./docker/django/Dockerfile
            args:
                - MYENV=${MYENV:-prod}
        environment:
            TZ: Asia/Shanghai
        ports:
            - 9000:9000
        expose:
            - 9000
        restart: always
        volumes:
            - django_data:/backend/static
    design-web:
        container_name: design-web
        build:
            context: ./
            dockerfile: ./docker/web/Dockerfile
            args:
                - MYENV=${MYENV:-prod}
        depends_on:
            - design-django
        ports:
            - 9001:9001
        expose:
            - 9001
        volumes:
            - ./docker/web/nginx.conf:/etc/nginx/conf.d/fuadmin.conf
        environment:
            - TZ='Asia/Shanghai'
        privileged: true # Add this line to enable --privileged
        ulimits:
            nofile:
                soft: 655350
                hard: 655350

    design-screenshots:
        container_name: design-screenshots
        build:
            context: ./
            dockerfile: ./docker/screenshot/Dockerfile
            args:
                - MYENV=${MYENV:-prod}
        ports:
            - 9002:9002
        expose:
            - 9002
        environment:
            - TZ='Asia/Shanghai'
        privileged: true # Add this line to enable --privileged
        ulimits:
            nofile:
                soft: 655350
                hard: 655350

    design-rembg:
        image: danielgatis/rembg
        container_name: design-rembg
        command: s
        ports:
            - 9003:5000
        expose:
            - 9003
        environment:
            - TZ=Asia/Shanghai
        restart: always

    design-file:
        container_name: design-file
        image: nginx:1.19.3-alpine
        ports:
            - 9004:9004
        expose:
            - 9004
        volumes:
            - ./docker/file/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./backend/static:/usr/share/nginx/html
        restart: always

volumes:
    django_data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /var/local/design
